import {
  ArrowLeftRight,
  Banknote,
  Baby,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  Bus,
  Camera,
  Car,
  Clapperboard,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Ellipsis,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  HeartPulse,
  Home,
  Laptop,
  Landmark,
  Music,
  Newspaper,
  PawPrint,
  Phone,
  PiggyBank,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Train,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";


export const CATEGORY_ICONS = {
  utensils: Utensils,
  "shopping-bag": ShoppingBag,
  car: Car,
  clapperboard: Clapperboard,
  receipt: Receipt,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  plane: Plane,
  home: Home,
  repeat: Repeat,
  tag: Tag,
  briefcase: Briefcase,
  laptop: Laptop,
  store: Store,
  "trending-up": TrendingUp,
  gift: Gift,
  coffee: Coffee,
  pizza: Pizza,
  dumbbell: Dumbbell,
  film: Film,
  music: Music,
  "book-open": BookOpen,
  wrench: Wrench,
  baby: Baby,
  "paw-print": PawPrint,
  shirt: Shirt,
  "gamepad-2": Gamepad2,
  "shopping-cart": ShoppingCart,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  phone: Phone,
  newspaper: Newspaper,
  bike: Bike,
  bus: Bus,
  train: Train,
  fuel: Fuel,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  coins: TrendingUp,
  bitcoin: Bitcoin,
  camera: Camera,
  globe: Globe,
  sparkles: Sparkles,
  star: Star,
  scissors: Scissors,
} as Record<string, LucideIcon>;

export type CategoryIconName = keyof typeof CATEGORY_ICONS;

export const CATEGORY_ICON_OPTIONS: { name: string; Icon: LucideIcon }[] = Object.entries(
  CATEGORY_ICONS,
).map(([name, Icon]) => ({ name, Icon }));

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? Tag;
}

export const PAYMENT_METHOD_ICONS: Record<string, LucideIcon> = {
  CASH: Banknote,
  BANK_TRANSFER: ArrowLeftRight,
  CREDIT_CARD: CreditCard,
  DEBIT_CARD: Wallet,
  UPI: Smartphone,
  OTHER: Ellipsis,
};

export function getPaymentMethodIcon(method: string): LucideIcon {
  return PAYMENT_METHOD_ICONS[method] ?? Ellipsis;
}
